### ISSUE TITLE
New post type "resource" back-end

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#467]
This post represents a physical resource. e.g. A lemon tree that people can pick from, or a community garden plot with open beds…

- [x] Location is required 
- [x] Track if resource is still available or not
- [x] Include time-frame (end times) to availability of resources

- [ ] Question: do we want to track amounts as a separate field? Like there are 5 apple trees to give away here

- [ ] Question: How is this different from an Offer? Maybe it’s just a specific type of offer? But it does have a different feel, more long running. More meant for the map. It could in the future have additional fields like amount, cost, etc. and eventually could lead to a marketplace.

**Comment by Mariette27** [comment]
A resource might be an offer, but what about a natural resource like a patch of osha or those lemon trees if we choose only to tend them against an upcoming blight? Then the tree might not be on offer (maybe not even fully visible as far as all its details are consider if the poster wants to be coy) so it does seem more like a resource. Offers might be a type of event with this logic. I'm really unsure and am delving deeper into REA https://www.youtube.com/watch?v=7lvSgsqdBhM

**Comment by Mariette27** [comment]
I got some more input from Liz T today. It came up naturally: From Liz Taggart “Eating clubs and recipe sharing circles as communities within Mycelia (what is our sense of belonging for the chefs and eaters?) James Beard community of chefs would come out to the (my) farm to see the harvest, to see how the plants grew, they would look at the seed pods, and then they would have a deep connection to the expression of the plants.” So libraries; knowledge repositories, long tail profiles = resources too

**Comment by cmonfreda** [comment]
- Defining Resources (as well as Offers) within or consistent with an REA framework seems  important--although I don't know enough yet to say exactly why or how they'd be meaningfully integrated with other kinds of posts and functions within such a framework.

- While Offers imply that the person making the offer owns or otherwise has some authority over it, this isn't necessary the case for Resources, which will carry context-specific conditions, and be public or private, open-access or communally owned and managed. To manage a commons effectively there actually has to be some way to define and enforce rules of access and use. Other (non-commons) Resources might truly be open to anyone, first-come, first-serve. Or they might be privately owned and available for a fee or in-kind trade, etc. These types of distinctions might be handled to some point in the Resource description, but there are limits to that. And posting a Resource to a community isn't necessarily the same things as granting access to that Resource. Here REA logic might come in handy.

- Keeping track of, say, the 5 apple trees in the question above requires some responsibility to monitor the Resource after the post is up. Also, this ties into the second point about keeping track of whether the Resource is still available or not (which might be tricky if the people making the post know the Resource is available but aren't there in person to check), e.g. if all 5 apple trees have been given away.

- In general, it seems like Offers get the thing to the person who needs it, while with Resources the person in need goes to the thing.

- What counts as a Resource depends on someone's ability to make use of it to produce value. For example, a degraded field might be available for restoration but not really useful for growing things until it is made fertile again. Until then it's more of a potential Resource than an actual one. Other Resources like biodiversity might support overall ecosystem functioning or genetic information but not really supportive of direct consumption or easily used up. Ecologists for example distinguish between four kinds of ecosystem services: provisioning, regulating, supporting, and cultural. Maybe too fine a point to matter here but maybe important to think about too.

**Comment by Mariette27** [comment]
"while with Resources the person in need goes to the thing." this
underscores a foundational difference in action/interaction and feels
correct to me as not being part of an offering which is ripe for immediate
action/transaction. Also, a wonderful point as well as the levels of
resource within the context of ecosystem: "service" which is in fact
different than an offer because the systemic role of the resource is more
durable and complex than an individualized offer.

**Comment by brodeur** [comment]
An offer is the event of making a resource available to others

**Comment by tibetsprague** [comment]
Another thought, ive heard other people talk about wanting to have "resource" libraries in Hylo, but they are referring to documents, links to websites, etc. These are long living artifacts that people want to be able to find easily in the future. Would we use the same post type "Resource" for those? Or just aggregate all links/attachments from all posts into this type of library?
