### ISSUE TITLE
Get sockets working locally in the dev environment

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#688]

**Comment by lorenjohnson** [comment]
Some interesting observations:

Sockets actually do work locally for me with Mobile between a local running backend and an App and Web instance also both local. So the current issue for mobile is that it’s breaking in Production for yet unknown reasons. 

However, in brief testing between 2 Web sessions running locally off the local backend, it doesn’t work. One of the browsers still receives the socket events from Mobile and the other doesn't. So antidotally it seems the issue is possibly with ID'ing the socket when going to the same IP address with different sessions (the Mobile App would have it's own local IP address)...

**Comment by lorenjohnson** [comment]
After careful attention to what is in `.env` config for `hylo-evo` and `HyloReactNative` and testing sockets seem to work fine in development mode on both platforms when working off a local `hylo-node` API instance. 

There really wasn't anything unexpected, but I did have some noise in my own `.env` files both for `hylo-evo` and `HyloReactNative` making it break.

A couple notes: 

1) `SOCKET_HOST` which is specified in addition to `API_HOST` in `hylo-evo` doesn't seem to have any use any more (currently only relevant outside of production anyway).

2) The current `onlyAllowOrigins` array in `config/env/production.js` on `hylo-node` specifies `http://localhost:3000` and `https://localhost:3000` as valid. We should also add the current default `hylo-evo` dev port of 9000. Without that in the less often case of setting your local `hylo-evo` instance to point to the production API sockets connections will not successfully authenticate. 

...

Still testing/confirming mobile production sockets function.
